service: football-god
frameworkVersion: '2'

plugins:
  - serverless-python-requirements

variablesResolutionMode: 20210326
custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  region: eu-central-1
  runtime: python3.8
  lambdaHashingVersion: 20201221

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  poll:
    handler: handler.send_poll
    events:
     - schedule: cron(30 12 ? * MON *)
    environment: ${ssm:/aws/reference/secretsmanager/football-god-env}
